services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/backend/data
    environment:
      - OLLAMA_API_BASE=http://host.docker.internal:11434
      - WEBUI_AUTH=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
  open-terminal:
    image: ghcr.io/open-webui/open-terminal
    container_name: open-terminal
    volumes:
      - ./open-terminal:/home/user
    environment:
      - OPEN_TERMINAL_API_KEY=Kiddbb0efjYWBBbufMChpRYzImHxbXZA

